name: student_performance_monitor
description: Student Performance Monitor — Track grades, attendance, assignments & performance.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # BLoC
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5

  # Charts
  fl_chart: ^0.69.0

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
