// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoaAm-GsGngOdeUHpee8pLz1EVLKcy2A',
    appId: '1:926477239761:web:58ed47265b74a5c0278cf0',
    messagingSenderId: '926477239761',
    projectId: 'edutrack-18269',
    authDomain: 'edutrack-18269.firebaseapp.com',
    storageBucket: 'edutrack-18269.firebasestorage.app',
    measurementId: 'G-63DT6X7P0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pcD_fNMnN4ZSo4n_feL3Z28g4omDsmQ',
    appId: '1:926477239761:android:04a14b097d7045d7278cf0',
    messagingSenderId: '926477239761',
    projectId: 'edutrack-18269',
    storageBucket: 'edutrack-18269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nDAgNXxBNMS6Q61SfqoH_4MDzp6LU2c',
    appId: '1:926477239761:ios:d2c054aa8398e45f278cf0',
    messagingSenderId: '926477239761',
    projectId: 'edutrack-18269',
    storageBucket: 'edutrack-18269.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );
}
